### ISSUE TITLE
Setup: Factory Girl methods could be included by default

### ISSUE THREAD

**Issue by IgorMarques** [Codeminer42/code42template#35]
After writing my first specs after the setup, I had to add the following config to make them pass:

```ruby
RSpec.configure do |config|
  config.include FactoryGirl::Syntax::Methods
end
```

I believe this could be included by default.

**Comment by thiagoa** [comment]
:+1: Will do

**Comment by thiagoa** [comment]
I've come to the conclusion that it's better to prefix every method call with `FactoryGirl`. Why?

- Factories are global. Having `FactoryGirl::Syntax::Methods` toggled on by default would reduce verbosity, but would end up sweeping the dirt under the rug by hiding the aforementioned fact.
- Having the `FactoryGirl` namespace by default in method calls makes FG calls easily scannable with grep. Ruby code bases are scannable with grep, so that's a win.

In my opinion, the benefits I've mentioned outweigh the advantages of `FactoryGirl::Syntax::Methods`. A bit of verbosity doesn't hurt and doesn't contribute on making specs uglier.
