### ISSUE TITLE
Failure in the code42-template@0.0.1 test:integration script

### ISSUE THREAD

**Issue by margOnline** [Codeminer42/code42template#49]
Following [Go Full Stack Rails: The FrontEnd, Part 1](https://blog.codeminer42.com/go-full-stack-rails-the-frontend-part-1-1b889c919b4a#.4p6b32e8z),  when running the example.spec.js integration test, I receive the following error.
`'NODE_ENV=test NODE_PATH='./app/assets/javascripts' karma start config/karma.conf.js'`

I'm using node version 6.8.1 and npm version 3.10.8

![screen shot 2016-11-09 at 11 39 39](https://cloud.githubusercontent.com/assets/3481059/20137317/9d74d0f4-a671-11e6-9b5e-a0e5b270b22a.png)

**Comment by thiagoa** [comment]
@margOnline Hi, which operation system are you using? Can you run `bin/setup` and check if it solves the problem?

**Comment by talyssonoc** [comment]
@thiagoa maybe we could use [cross-env](https://www.npmjs.com/package/cross-env) to make it cross-platform, what do you think?

**Comment by thiagoa** [comment]
@talyssonoc Seems a good idea

**Comment by margOnline** [comment]
Running `bin/setup` failed with 
`don't know how to build task 'db:setup'`

Rails version is 5.0.0.1

I dont seem to have any of the rails db commands. 

I can run the rspec tests and `npm run test:unit` but `npm run test:integration` fails as above.

**Comment by thiagoa** [comment]
@margOnline Have you tried `npm install`?

**Comment by margOnline** [comment]
yes - node version is 6.8.1

**Comment by thiagoa** [comment]
@margOnline OK, I guess I'm getting the picture.

Integration tests depend on [PhantomJS](http://phantomjs.org/), do you have it installed on your machine? If not, you can probably install it via [homebrew](http://brew.sh) and try running `npm run test:integration` again.

I've tried uninstalling PhantomJS on my machine and got the same output of yours, but there's some important information around it. I wonder if you are having the same issue:

![Uploading Screenshot from 2016-11-10 10-29-02.png…]()

If Phantom is already installed on your machine, please provide the complete error output including the command itself and any text after it.

As for the `db:setup` error, I guess the reason is because the setup script is not prepending Rails commands with `bundle exec`, so it is not factoring in one of the possible situations where commands can't be run without bundle exec. Can you try running `bundle exec rake db:setup` manually and see if it errors out?

**Comment by thiagoa** [comment]
@margOnline The screenshot did not upload, so I updated the comment above with a Dropbox link to it.

**Comment by margOnline** [comment]
I found an error in my code 😞 . I had omitted the curly braces in the function declaration:

`function renderCartTotal(domNode, itemPrices)` instead of 
`function renderCartTotal({domNode, itemPrices})`

I am not familiar with this syntax, though I've now discovered it is called 'destructuring assignment' in ecma6. 

I'm still surprised that I don't have access to the rails db commands. `bundle exec rake db:setup` also fails with `Don't know how to build task 'db:setup'`. Running `rails -h` shows alot of tasks that used to be rake tasks such as routes, but none of the db ones.

However all tests are passing now and I can continue with the tutorial. Thanks for your help and apologies for the red herring!
